### ISSUE TITLE
Help needed!

### ISSUE THREAD

**Issue by mairm1340** [sjhloco/asa_acl_report#7]
amrim@z370: ~/Desktop/CiscoAutomation 
┌──────────────────────────────────────────────
└─> python asa_acl_report/asa_acl_report_v3.py -f acl.txt

============================== ASA ACL Auditor v0.3 (tested 9.8) ==============================
Checking the options entered are valid...
The output file already exist, do you want to overwrite it?
y or n: y
!!! ERROR - No hitcnt in acl.txt, make sure is output of "show RUN access-list" and NOT "show access-list" !!!
                                                                                                                 

do we save the output of show access-list or show run access-list ?

I did match the output of the acl.txt in the example folder and it is like the output of show access-list

I badly need this but not able to figure out what I am doing wrong

**IF I   run on the file available in acl.txt which I renamed to acl-original.txt the output is saved--- this is clear that the installation and dependencies are taken care.

amrim@z370: ~/Desktop/CiscoAutomation 
┌──────────────────────────────────────────────
└─> python asa_acl_report/asa_acl_report_v3.py -f /home/amrim/Desktop/CiscoAutomation/asa_acl_report/example_acls/acl-original.txt 

============================== ASA ACL Auditor v0.3 (tested 9.8) ==============================
Checking the options entered are valid...
The output file already exist, do you want to overwrite it?
y or n: y
Gathering ACL info from the File...
Formatting the ACL data...
Creating the spreadsheet...
File /home/amrim/10.10.10.1_ACLreport_20221202.xlsx has been created

**Comment by mairm1340** [comment]
acl file attached
[acl.txt](https://github.com/sjhloco/asa_acl_report/files/10141426/acl.txt)

**Comment by mairm1340** [comment]
Mamlab-FW01# sh ver 

Cisco Adaptive Security Appliance Software Version 9.16(3) 


└─> python asa_acl_report/asa_acl_report_v3.py -d mohammed@192.168.11.254

============================== ASA ACL Auditor v0.3 (tested 9.8) ==============================
Checking the options entered are valid...
Enter the ASA password: 
Gathering ACL info from the ASA...
Formatting the ACL data...
Traceback (most recent call last):
  File "/home/amrim/Desktop/CiscoAutomation/asa_acl_report/asa_acl_report_v3.py", line 411, in <module>
    main()
  File "/home/amrim/Desktop/CiscoAutomation/asa_acl_report/asa_acl_report_v3.py", line 404, in main
    acl = run1.format_acl()
  File "/home/amrim/Desktop/CiscoAutomation/asa_acl_report/asa_acl_report_v3.py", line 304, in format_acl
    src_pfx = IPv4Network((ace[4], ace[5])).with_prefixlen	   # Add prefix to the src_IP
  File "/usr/lib/python3.10/ipaddress.py", line 1507, in __init__
    raise ValueError('%s has host bits set' % self)
ValueError: 255.255.255.0/0 has host bits set

**Comment by sjhloco** [comment]
I haven't really used this for years so cant guarantee anything with it. Yeah it should be *show access-list* so is a typo. Looking at your file you have none access list lines in it like this between ACLs.

```
access-list cached ACL log flows: total 0, denied 0 (deny-flow-max 4096)
            alert-interval 300
```

If you remove these, any standard ACLs (must be extended ACLs only), inactive ACLS and FQDNs it should work. This was created on an older version of code with not many of these features on it 

In terms of running against a device, that error looks like it is because of standard ACLs. I gave up on this project and moved on to this https://github.com/sjhloco/firewall_policy_report. If running against a device would suggest using that as I think I included a fix to ignore standard ACLs and a few other more advanced objects that broke this project

**Comment by mairm1340** [comment]
Thank you so much
I will take a look at that.
